// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnaruuktgvgcikwuttqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuYXJ1dWt0Z3ZnY2lrd3V0dHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDA3NzMsImV4cCI6MjA2NDQxNjc3M30.qyZSEfEB4Se-b0xT6PvI74pwlKx0E7YktFb2fTvzWBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);